NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.blockchain.itrus.com.cn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.blockchain.itrus.com.cn-cert.pem
    OrganizationalUnitIdentifier: peer
