version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  couchdb0.blockchain.bxsfjdzx.gov.cn:
    hostname: couchdb0.blockchain.bxsfjdzx.gov.cn
    image: hyperledger/fabric-couchdb:latest
    networks:
      hyperledger-ov:
        aliases:
        - couchdb0.blockchain.bxsfjdzx.gov.cn
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=couchdbpasswd
    volumes:
    - /data/couchdb/couchdb0.blockchain.bxsfjdzx.gov.cn:/opt/couchdb/data
    restart: unless-stopped
    privileged: true
    user: root
    ports:
    - 5984:5984
  peer0.blockchain.bxsfjdzx.gov.cn:
    hostname: peer0.blockchain.bxsfjdzx.gov.cn
    image: hyperledger/fabric-peer:latest
    networks:
      hyperledger-ov:
        aliases:
        - peer0.blockchain.bxsfjdzx.gov.cn
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_PEER=warning
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=false
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.blockchain.bxsfjdzx.gov.cn
    - CORE_PEER_ADDRESS=peer0.blockchain.bxsfjdzx.gov.cn:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain.bxsfjdzx.gov.cn:7051
    - CORE_PEER_LOCALMSPID=blockchainbxsfjdzxgovcnMSP
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.blockchain.bxsfjdzx.gov.cn:5984
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.blockchain.bxsfjdzx.gov.cn:7051
    - GODEBUG=netdns=go
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdbpasswd
    - CORE_LEDGER_STATE_COUCHDBCONFIG_QUERYLIMIT=200
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
    - /root/hosts:/etc/hosts
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/blockchain.bxsfjdzx.gov.cn/peers/peer0.blockchain.bxsfjdzx.gov.cn/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/blockchain.bxsfjdzx.gov.cn/peers/peer0.blockchain.bxsfjdzx.gov.cn/tls:/etc/hyperledger/fabric/tls
    - /data/peer/peer0.blockchain.bxsfjdzx.gov.cn:/var/hyperledger/production
    restart: on-failure
    privileged: true
    user: root
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - couchdb0.blockchain.bxsfjdzx.gov.cn
