version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  zookeeper1.bqj.cn:
    hostname: zookeeper1.bqj.cn
    image: hyperledger/fabric-zookeeper:latest
    network_mode: host
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
    - ZOO_MY_ID=2
    - ZOO_SERVERS=server.1=zookeeper0.bqj.cn:2888:3888 server.2=zookeeper1.bqj.cn:2888:3888 server.3=zookeeper2.bqj.cn:2888:3888
    volumes:
    - ./hosts:/etc/hosts
    - /data/zookeeper/zookeeper1.bqj.cn/data:/data
    - /data/zookeeper/zookeeper1.bqj.cn/datalog:/datalog
    restart: always
    ports:
    - 2888:2888
    - 3888:3888
    - 2181:2181
